"""empty message

Revision ID: 3d8885deafa8
Revises: 1830ad31af41
Create Date: 2024-12-18 13:47:13.664892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8885deafa8'
down_revision = '1830ad31af41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_booking', schema=None) as batch_op:
        batch_op.alter_column('price_range',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_booking', schema=None) as batch_op:
        batch_op.alter_column('price_range',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
