"""empty message

Revision ID: b7710720ce3e
Revises: 3d8885deafa8
Create Date: 2024-12-18 15:36:09.627082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7710720ce3e'
down_revision = '3d8885deafa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.drop_column('price_range')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_range', sa.FLOAT(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
