"""empty message

Revision ID: f3de0500f896
Revises: 
Create Date: 2024-12-17 23:34:57.863829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3de0500f896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engineering_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=False),
    sa.Column('client_email', sa.String(length=120), nullable=False),
    sa.Column('client_phone', sa.String(length=15), nullable=True),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('project_manager', sa.String(length=80), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('project_start_date', sa.String(length=50), nullable=False),
    sa.Column('project_end_date', sa.String(length=50), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=False),
    sa.Column('client_email', sa.String(length=120), nullable=False),
    sa.Column('client_phone', sa.String(length=15), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date_time', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('guests', sa.String(length=10), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('review')
    op.drop_table('performance_booking')
    op.drop_table('engineering_booking')
    op.drop_table('contact')
    # ### end Alembic commands ###
